# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # and ignore if there are only changes to .md-files, such as README.md
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true
    
    strategy:
      matrix:
        release: [R2021b]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
        
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: cache
        with:
          path: .git/lfs
          key: lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      
      - name: Git LFS Pull
        if: steps.cache.outputs.cache-hit != 'true'
        run: git lfs pull
